name: Upload Python Package

on:
  release:
    types: [published]  # Triggers when a release is published

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Build release distributions
      - name: Build release distributions
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build

      # Step 4: Upload build artifacts for the next job
      - name: Upload distributions as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build  # This job runs after `release-build`

    steps:
      # Step 1: Download the built artifacts
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      # Step 2: Publish to PyPI
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
